<?php
/**
* @file
* A description of what your module does.
*/

function mymodule_form_alter(&$form, $form_state, $form_id){
    if($form_id == 'webform_client_form_1') {
        $form['#submit'] []= 'mymodule_form_submit_handler';
    }
}

function mymodule_form_submit_handler($form, &$form_state) {
    unset($_REQUEST['destination']);
    unset($form['#redirect']);

    $form_state['redirect']  = 'http://google.com';

}
